### ISSUE TITLE
OMV 4.x support

### ISSUE THREAD

**Issue by jmatraszek** [OpenMediaVault-Plugin-Developers/openmediavault-deluge#4]
Is there any chance that the plugin will get OMV 4.x support?

**Comment by ryecoaaron** [comment]
No.  The plugin has been dropped in favor of docker - https://forum.openmediavault.org/index.php/Thread/19553-OMV-Docker-plugin-media-server-Plex-PlexPy-Ombi-Libresonic-NZBGet-ruTorrent-Sona/

**Comment by jmatraszek** [comment]
Okay, thanks for the info. Will give docker version a try. :+1:
